### ISSUE TITLE
Headers does not match content

### ISSUE THREAD

**Issue by nlehuby** [CanalTP/osm-transit-extractor#21]
There is something wrong with the headers of somes csv files :

cat /tmp/osm-transit-extractor_routes.csv |head |xsv select '!shape'|xsv table
>> route_id                name                                     code  destination    origin         mode  colour                                                       operator                        network
>> Route:Relation:7406209  Trotro 31 : 37 → Abeka Lapaz             31    Abeka Lapaz    37                   Lapaz No.2 Branch of G.P.R.T.U                               trô trô                         bus
>> Route:Relation:7406251  Trotro 282 : Shalom → Kaneshie           282   Kaneshie       Shalom               Kaneshie No. 2 Branch of GPRTU                               trô trô                         bus

cat /tmp/osm-transit-extractor_lines.csv |head |xsv select '!shape'|xsv table
>> id                     name                                      code  operator  network                                                      mode     colour
>> Line:Relation:7406210  Trotro 31 : Abeka Lapaz ↔ 37              31              Lapaz No.2 Branch of G.P.R.T.U                               trô trô  bus

**Comment by prhod** [comment]
:+1:
