### ISSUE TITLE
StopPoint vs StopPosition vs Platform

### ISSUE THREAD

**Issue by nlehuby** [CanalTP/osm-transit-extractor#27]
We need to improve the stop_position vs platform handling :

The stop file have only `bus_stop`s, most of them are `platform`s.
But the route_stop file have both `stop_position`s and `platform`s. So you have items with `stop_id` from the route_stop file that does not match anything in your extract.

We should either extract the `stop_position`s too (and add the roles in the route_stop file), either filter them in the route_stop file.

**Comment by prhod** [comment]
I think this issue is resolved by https://github.com/CanalTP/osm-transit-extractor/pull/37, I'm closing it
